# Generated by Django 5.0 on 2026-06-17 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_userprofile_is_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('US', 'United States'), ('AU', 'Australia'), ('CA', 'Canada'), ('UK', 'United Kingdom')], max_length=2)),
                ('number_type', models.CharField(choices=[('mobile', 'Mobile'), ('vip', 'VIP Number')], max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('telnyx_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.99, max_digits=10)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('telnyx_connection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.phonenumberinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
