# Generated by Django 5.0 on 2026-06-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_phonenumberinventory_phonenumberplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='call_type',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='caller_number',
            new_name='from_number',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='did_number',
            new_name='to_number',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='calllog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calllog',
            name='status',
            field=models.CharField(default='initiated', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='telnyx_call_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
